model_name: "bert-base-uncased"       # Pretrained model from Hugging Face
checkpoint_dir: "checkpoints"         # Directory to save model checkpoints
checkpoint_filename: "best_model-{epoch}"  # Naming format for saved checkpoints
monitor_metric: "val_loss"            # Metric to monitor for checkpoint saving
monitor_mode: "min"                   # Mode for monitoring the metric (min or max)
log_dir: "logs"                       # Directory for saving training logs
max_epochs: 10                        # Number of epochs for training
final_model_path: "model/final_model.pth"  # Final model path after training
model_dir: "model"                   # Directory for saving the final model
