defaults:
  - data: data_paths   # Reference to the data paths configuration file
  - model: model_config  # Reference to the model configuration file
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
hydra:
  run:
    dir: .
  output_subdir: null
