defaults:
  - data: data_paths
  - model: model_config
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
mlflow:
  tracking_uri: "http://mlflow-service:5000"
  experiment_name: "example_exp"
hydra:
  run:
    dir: .
  output_subdir: null
